name: movie
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  cached_network_image: 3.3.1
  freezed_annotation: ^2.4.1
  http: ^1.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.4.9
  flutter_gen_runner: 5.4.0
  flutter_lints: ^4.0.0
  freezed: 2.4.7

flutter:
  uses-material-design: true